name: 'Common - Android'
description: 'Common setup for Android workflows'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        java-version-file: '.java-version'
        distribution: 'adopt'
        cache: 'gradle'
        cache-dependency-path: ./gradle/*.versions.toml
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
