name: android-test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "app/src/main/**"

permissions:
  checks: write

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: |
          ./gradlew emojify:preTest
          ./gradlew emojify:test --stacktrace
          ./gradlew emojify:postTest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

  instrumented:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 23
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}
      - name: Publish Integrated Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/androidTest-results/**/TEST-*.xml'
