name: android-publish-artifact

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "app/src/main/**"

permissions:
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          running-workflow-name: android-publish-artifact
          check-name: android-unit-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to local maven
        run: |
          ./gradlew build publishMavenPublicationToMavenLocal
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publications
          path: ~/.m2/repository/io/wax911/emoji/
