name: gradle-dokka-html

on:
  push:
    branches: [ develop ]

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate docs with dokka
        run: ./gradlew emojify:dokkaHtml

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: docs # The branch the action should deploy to.
          folder: emojify/build/docs/dokka # The folder the action should deploy.
