name: Release Drafter

on:
  push:
    branches:
      - 'develop'

permissions:
  contents: read

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: release-drafter/release-drafter@v7
        id: release_drafter
        with:
          config-name: release-drafter-config.yml
          commitish: develop
          token: ${{ steps.app-token.outputs.token }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          event-type: version-update-and-push
          client-payload: '{"version": "${{ steps.release_drafter.outputs.resolved_version }}"}'
